<?php
/**
 * Plugin Name: JSON Calendar
 * Description: Fetches calendar entries from a JSON endpoint and displays them with the [json_calendar] shortcode.
 * Version: 1.0.0
 * Author: x39akkdjf1
 * License: GPL-2.0-or-later
 * Requires at least: 5.8
 * Requires PHP: 7.4
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class JSON_Calendar_WP {
	const OPTION_ENDPOINT = 'json_calendar_wp_endpoint';
	const SHORTCODE = 'json_calendar';

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_settings_page' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
		add_shortcode( self::SHORTCODE, array( $this, 'render_shortcode' ) );
	}

	public function add_settings_page() {
		add_options_page(
			__( 'JSON Calendar', 'json-calendar-wp' ),
			__( 'JSON Calendar', 'json-calendar-wp' ),
			'manage_options',
			'json-calendar-wp',
			array( $this, 'render_settings_page' )
		);
	}

	public function register_settings() {
		register_setting(
			'json_calendar_wp_settings',
			self::OPTION_ENDPOINT,
			array(
				'type'              => 'string',
				'sanitize_callback' => 'esc_url_raw',
				'default'           => '',
			)
		);
	}

	public function render_settings_page() {
		?>
		<div class="wrap">
			<h1><?php echo esc_html__( 'JSON Calendar', 'json-calendar-wp' ); ?></h1>
			<p><?php echo esc_html__( 'Set the URL of the JSON generated by json_calendar_generator, then add [json_calendar] to any page or post.', 'json-calendar-wp' ); ?></p>
			<form method="post" action="options.php">
				<?php settings_fields( 'json_calendar_wp_settings' ); ?>
				<table class="form-table" role="presentation">
					<tr>
						<th scope="row"><label for="json_calendar_wp_endpoint"><?php echo esc_html__( 'JSON endpoint URL', 'json-calendar-wp' ); ?></label></th>
						<td>
							<input type="url" class="regular-text" id="json_calendar_wp_endpoint" name="<?php echo esc_attr( self::OPTION_ENDPOINT ); ?>" value="<?php echo esc_attr( get_option( self::OPTION_ENDPOINT, '' ) ); ?>" placeholder="https://example.com/kalender/199.json" required />
							<p class="description"><?php echo esc_html__( 'The endpoint must return a JSON array, or an object containing an entries array.', 'json-calendar-wp' ); ?></p>
						</td>
					</tr>
				</table>
				<?php submit_button(); ?>
			</form>
		</div>
		<?php
	}

	public function render_shortcode( $atts ) {
		$atts = shortcode_atts(
			array(
				'url'   => get_option( self::OPTION_ENDPOINT, '' ),
				'limit' => 0,
			),
			$atts,
			self::SHORTCODE
		);

		$url = esc_url_raw( $atts['url'] );
		if ( empty( $url ) || ! wp_http_validate_url( $url ) ) {
			return current_user_can( 'manage_options' )
				? '<p class="json-calendar-error">' . esc_html__( 'Configure a JSON endpoint under Settings → JSON Calendar.', 'json-calendar-wp' ) . '</p>'
				: '';
		}

		$cache_key = 'json_calendar_' . md5( $url );
		$data      = get_transient( $cache_key );
		if ( false === $data ) {
			$response = wp_safe_remote_get(
				$url,
				array(
					'timeout'    => 10,
					'headers'    => array( 'Accept' => 'application/json' ),
					'user-agent' => 'JSON Calendar WordPress Plugin/1.0.0',
				)
			);

			if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
				return '<p class="json-calendar-error">' . esc_html__( 'Calendar entries are temporarily unavailable.', 'json-calendar-wp' ) . '</p>';
			}

			$data = json_decode( wp_remote_retrieve_body( $response ), true );
			if ( JSON_ERROR_NONE !== json_last_error() ) {
				return '<p class="json-calendar-error">' . esc_html__( 'The calendar endpoint returned invalid JSON.', 'json-calendar-wp' ) . '</p>';
			}
			set_transient( $cache_key, $data, 15 * MINUTE_IN_SECONDS );
		}

		$entries = $this->get_entries( $data );
		if ( empty( $entries ) ) {
			return '<p class="json-calendar-empty">' . esc_html__( 'No calendar entries found.', 'json-calendar-wp' ) . '</p>';
		}

		$limit = absint( $atts['limit'] );
		if ( $limit > 0 ) {
			$entries = array_slice( $entries, 0, $limit );
		}

		$output = '<div class="json-calendar"><ul class="json-calendar-list">';
		foreach ( $entries as $entry ) {
			if ( ! is_array( $entry ) ) {
				continue;
			}
			$title       = $this->value( $entry, array( 'title', 'name', 'summary' ), __( 'Untitled event', 'json-calendar-wp' ) );
			$start       = $this->value( $entry, array( 'start', 'start_date', 'date', 'datetime' ) );
			$end         = $this->value( $entry, array( 'end', 'end_date' ) );
			$description = $this->value( $entry, array( 'description', 'details', 'content' ) );
			$location    = $this->value( $entry, array( 'location', 'venue' ) );
			$link        = $this->value( $entry, array( 'url', 'link', 'permalink' ) );
			$image       = $this->first_image( $entry );

			$output .= '<li class="json-calendar-entry">';
			if ( $image ) {
				$output .= '<div class="json-calendar-cover" style="position:relative;overflow:hidden;display:block;">';
				$output .= '<img src="' . esc_url( $image ) . '" alt="' . esc_attr( $title ) . '" style="display:block;width:100%;height:clamp(320px,40vw,620px);object-fit:cover;object-position:center;" />';
				$output .= '<div class="wp-block-cover__inner-container has-global-padding is-layout-constrained wp-block-cover-is-layout-constrained" style="position:absolute;right:0;bottom:0;left:0;padding:clamp(1rem,2vw,2.5rem);box-sizing:border-box;text-align:right;color:#fff;display:flex;flex-direction:column;align-items:flex-end;justify-content:flex-end;">';
				$output .= '<div style="font-family:Arial,Helvetica,sans-serif;font-size:clamp(1rem,1.6vw,1.8rem);font-weight:400;line-height:1.1;letter-spacing:-0.02em;color:#fff;text-transform:none;">' . esc_html__( 'Next up', 'json-calendar-wp' ) . '</div>';
				$output .= '<h3 style="margin:0.2rem 0 0;color:#fff;font-family:Arial,Helvetica,sans-serif;font-size:clamp(2rem,4vw,4.5rem);font-weight:800;line-height:0.95;letter-spacing:-0.04em;text-transform:none;text-align:right;">' . esc_html( $title ) . '</h3>';
				$output .= '</div>';
				$output .= '</div>';
			} else {
				$output .= '<h3 class="json-calendar-title">' . esc_html( $title ) . '</h3>';
			}
			if ( $start ) {
				$output .= '<time class="json-calendar-date" datetime="' . esc_attr( $start ) . '">' . esc_html( $this->format_date( $start ) );
				if ( $end ) {
					$output .= ' – ' . esc_html( $this->format_date( $end ) );
				}
				$output .= '</time>';
			}
			if ( $location ) {
				$output .= '<div class="json-calendar-location">' . esc_html( $location ) . '</div>';
			}
			if ( $description ) {
				$output .= '<div class="json-calendar-description">' . wp_kses_post( $description ) . '</div>';
			}
			if ( $link && wp_http_validate_url( $link ) ) {
				$output .= '<a class="json-calendar-link" href="' . esc_url( $link ) . '">' . esc_html__( 'More information', 'json-calendar-wp' ) . '</a>';
			}
			$output .= '</li>';
		}
		$output .= '</ul></div>';

		return $output;
	}

	private function get_entries( $data ) {
		if ( isset( $data['entries'] ) && is_array( $data['entries'] ) ) {
			return $data['entries'];
		}
		if ( isset( $data['events'] ) && is_array( $data['events'] ) ) {
			return $data['events'];
		}
		return is_array( $data ) && array_is_list( $data ) ? $data : array();
	}

	private function first_image( $entry ) {
		if ( ! isset( $entry['image'] ) ) {
			return '';
		}

		$image = $entry['image'];
		if ( is_array( $image ) ) {
			$image = reset( $image );
		}
		if ( ! is_scalar( $image ) ) {
			return '';
		}

		$image = trim( (string) $image );
		if ( '' === $image ) {
			return '';
		}
		if ( 0 !== strpos( $image, 'http://' ) && 0 !== strpos( $image, 'https://' ) ) {
			$image = 'https://' . $image;
		}
		return wp_http_validate_url( $image ) ? $image : '';
	}

	private function value( $entry, $keys, $default = '' ) {
		foreach ( $keys as $key ) {
			if ( isset( $entry[ $key ] ) && is_scalar( $entry[ $key ] ) && '' !== (string) $entry[ $key ] ) {
				return (string) $entry[ $key ];
			}
		}
		return $default;
	}

	private function format_date( $date ) {
		$timestamp = strtotime( $date );
		return $timestamp ? wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), $timestamp ) : $date;
	}
}

new JSON_Calendar_WP();
