<?php
/**
 * Plugin Name: JSON Calendar
 * Description: Fetches calendar entries from a JSON endpoint and displays them with the [json_calendar] shortcode.
 * Version: 1.4.2
 * Author: x39akkdjf1
 * License: GPL-2.0-or-later
 * Requires at least: 5.8
 * Requires PHP: 7.4
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class JSON_Calendar_WP {
	const OPTION_ENDPOINT = 'json_calendar_wp_endpoint';
	const SHORTCODE = 'json_calendar';
	const CACHE_VERSION = '3';

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_settings_page' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
		add_shortcode( self::SHORTCODE, array( $this, 'render_shortcode' ) );
	}

	public function add_settings_page() {
		add_options_page( __( 'JSON Calendar', 'json-calendar-wp' ), __( 'JSON Calendar', 'json-calendar-wp' ), 'manage_options', 'json-calendar-wp', array( $this, 'render_settings_page' ) );
	}

	public function register_settings() {
		register_setting( 'json_calendar_wp_settings', self::OPTION_ENDPOINT, array( 'type' => 'string', 'sanitize_callback' => 'esc_url_raw', 'default' => '' ) );
	}

	public function render_settings_page() {
		?>
		<div class="wrap">
			<h1><?php echo esc_html__( 'JSON Calendar', 'json-calendar-wp' ); ?></h1>
			<p><?php echo esc_html__( 'Set the URL of the JSON generated by json_calendar_generator, then add [json_calendar] to any page or post.', 'json-calendar-wp' ); ?></p>
			<form method="post" action="options.php">
				<?php settings_fields( 'json_calendar_wp_settings' ); ?>
				<table class="form-table" role="presentation"><tr>
					<th scope="row"><label for="json_calendar_wp_endpoint"><?php echo esc_html__( 'JSON endpoint URL', 'json-calendar-wp' ); ?></label></th>
					<td><input type="url" class="regular-text" id="json_calendar_wp_endpoint" name="<?php echo esc_attr( self::OPTION_ENDPOINT ); ?>" value="<?php echo esc_attr( get_option( self::OPTION_ENDPOINT, '' ) ); ?>" placeholder="https://example.com/kalender/199.json" required /></td>
				</tr></table>
				<?php submit_button(); ?>
			</form>
		</div>
		<?php
	}

	public function render_shortcode( $atts ) {
		$atts = shortcode_atts( array( 'url' => get_option( self::OPTION_ENDPOINT, '' ), 'limit' => 0 ), $atts, self::SHORTCODE );
		$url = esc_url_raw( $atts['url'] );
		if ( empty( $url ) || ! wp_http_validate_url( $url ) ) {
			return current_user_can( 'manage_options' ) ? '<p class="json-calendar-error">' . esc_html__( 'Configure a JSON endpoint under Settings → JSON Calendar.', 'json-calendar-wp' ) . '</p>' : '';
		}

		$cache_key = 'json_calendar_' . self::CACHE_VERSION . '_' . md5( $url );
		$data = get_transient( $cache_key );
		if ( false === $data ) {
			$response = wp_safe_remote_get( $url, array( 'timeout' => 10, 'headers' => array( 'Accept' => 'application/json' ), 'user-agent' => 'JSON Calendar WordPress Plugin/1.4.2' ) );
			if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) return '<p class="json-calendar-error">' . esc_html__( 'Calendar entries are temporarily unavailable.', 'json-calendar-wp' ) . '</p>';
			$data = json_decode( wp_remote_retrieve_body( $response ), true );
			if ( JSON_ERROR_NONE !== json_last_error() ) return '<p class="json-calendar-error">' . esc_html__( 'The calendar endpoint returned invalid JSON.', 'json-calendar-wp' ) . '</p>';
			set_transient( $cache_key, $data, 15 * MINUTE_IN_SECONDS );
		}

		$entries = $this->filter_future_entries( $this->get_entries( $data ) );
		if ( empty( $entries ) ) return '<p class="json-calendar-empty">' . esc_html__( 'No upcoming calendar entries found.', 'json-calendar-wp' ) . '</p>';
		$limit = absint( $atts['limit'] );
		if ( $limit > 0 ) $entries = array_slice( $entries, 0, $limit );

		$instance = wp_unique_id( 'json-calendar-' );
		$id = esc_attr( $instance );
		$output = '<style>
			#' . $id . ' .json-calendar-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:1rem;list-style:none;margin:0;padding:0}
			#' . $id . ' .json-calendar-entry{perspective:1000px;outline:none}
			#' . $id . ' .json-calendar-card{position:relative;width:100%;transform-style:preserve-3d;transition:transform .55s ease;cursor:pointer}
			#' . $id . ' .json-calendar-entry.is-flipped .json-calendar-card,#' . $id . ' .json-calendar-entry:hover .json-calendar-card,#' . $id . ' .json-calendar-entry:focus-within .json-calendar-card{transform:rotateY(180deg)}
			#' . $id . ' .json-calendar-front{position:relative;width:100%;backface-visibility:hidden;-webkit-backface-visibility:hidden;overflow:hidden;border-radius:4px;background:#f5f5f5}
			#' . $id . ' .json-calendar-back{position:absolute;inset:0;box-sizing:border-box;padding:1.25rem;background:#fff;color:#000;border:1px solid #ddd;border-radius:4px;backface-visibility:hidden;-webkit-backface-visibility:hidden;transform:rotateY(180deg);overflow-y:auto}
			#' . $id . ' .json-calendar-image{display:block;width:100%;height:auto;object-fit:contain}
			#' . $id . ' .json-calendar-title{margin:0 0 .7rem;color:#000;font-size:1.35rem;line-height:1.2}
			#' . $id . ' .json-calendar-date,#' . $id . ' .json-calendar-time{margin:.25rem 0;color:#333;font-family:Arial,Helvetica,sans-serif;font-style:italic;font-size:.85rem}
			#' . $id . ' .json-calendar-description{margin:.8rem 0;color:#000;font-family:inherit;font-size:1rem;line-height:1.45}
			@media (hover:hover){#' . $id . ' .json-calendar-entry:hover .json-calendar-card{transform:rotateY(180deg)}}
		</style><div id="' . $id . '" class="json-calendar"><ul class="json-calendar-list">';

		foreach ( $entries as $entry ) {
			if ( ! is_array( $entry ) ) continue;
			$title = $this->value( $entry, array( 'title', 'name', 'summary' ), __( 'Untitled event', 'json-calendar-wp' ) );
			$date = $this->value( $entry, array( 'date', 'start_date' ) );
			$date_end = $this->value( $entry, array( 'date_end', 'end_date' ) );
			$time_start = $this->value( $entry, array( 'time_start' ) );
			$time_end = $this->value( $entry, array( 'time_end' ) );
			$description = $this->value( $entry, array( 'description', 'details', 'content' ) );
			$image = $this->first_image( $entry );
			$start_fallback = $this->date_time( $entry, 'date', 'time_start', array( 'start', 'datetime' ) );

			$output .= '<li class="json-calendar-entry" tabindex="0" aria-label="' . esc_attr( $title ) . '"><div class="json-calendar-card"><div class="json-calendar-front">';
			$output .= $image ? '<img class="json-calendar-image" src="' . esc_url( $image ) . '" alt="' . esc_attr( $title ) . '" loading="lazy" />' : '<div style="padding:1rem">' . esc_html( $title ) . '</div>';
			$output .= '</div><div class="json-calendar-back"><h2 class="json-calendar-title">' . esc_html( $title ) . '</h2>';
			if ( $date || $date_end || $start_fallback ) {
				$output .= '<div class="json-calendar-date">' . esc_html( $date ? $this->format_date_only( $date ) : $this->format_date( $start_fallback ) );
				if ( $date_end && $date_end !== $date ) $output .= ' – ' . esc_html( $this->format_date_only( $date_end ) );
				$output .= '</div>';
			}
			if ( $time_start || $time_end ) {
				$output .= '<div class="json-calendar-time">' . esc_html( $time_start );
				if ( $time_end ) $output .= ' – ' . esc_html( $time_end );
				$output .= '</div>';
			}
			if ( $description ) $output .= '<p class="json-calendar-description">' . wp_kses_post( $description ) . '</p>';
			$output .= '</div></div></li>';
		}
		$output .= '</ul><script>(function(){var root=document.getElementById(' . wp_json_encode( $instance ) . ');if(!root)return;root.querySelectorAll(".json-calendar-entry").forEach(function(card){card.addEventListener("click",function(){card.classList.toggle("is-flipped");});card.addEventListener("keydown",function(event){if(event.key==="Enter"||event.key===" "){event.preventDefault();card.classList.toggle("is-flipped");}if(event.key==="Escape")card.classList.remove("is-flipped");});});})();</script></div>';
		return $output;
	}

	private function get_entries( $data ) {
		if ( ! is_array( $data ) ) return array();
		if ( isset( $data['entries'] ) && is_array( $data['entries'] ) ) return $this->get_entries( $data['entries'] );
		if ( isset( $data['events'] ) && is_array( $data['events'] ) ) return $this->get_entries( $data['events'] );
		if ( $this->is_event( $data ) ) return array( $data );
		$entries = array();
		foreach ( $data as $reference => $entry ) if ( is_array( $entry ) ) foreach ( $this->get_entries( $entry ) as $nested_entry ) { if ( empty( $nested_entry['reference'] ) ) $nested_entry['reference'] = (string) $reference; $entries[] = $nested_entry; }
		return $entries;
	}

	private function is_event( $value ) { return is_array( $value ) && ( isset( $value['title'] ) || isset( $value['date'] ) || isset( $value['reference'] ) ); }

	private function filter_future_entries( $entries ) {
		$today = strtotime( wp_date( 'Y-m-d', current_time( 'timestamp' ) ) ); $filtered = array();
		foreach ( $entries as $entry ) { $start = $this->get_entry_start_timestamp( $entry ); $end = $this->get_entry_end_timestamp( $entry ); if ( ( false !== $start && $start >= $today ) || ( false !== $end && $end >= $today ) ) $filtered[] = $entry; }
		usort( $filtered, function( $a, $b ) { $left = $this->get_entry_start_timestamp( $a ); $right = $this->get_entry_start_timestamp( $b ); if ( false === $left ) $left = $this->get_entry_end_timestamp( $a ); if ( false === $right ) $right = $this->get_entry_end_timestamp( $b ); return ( false === $left || false === $right ) ? 0 : $left <=> $right; } );
		return $filtered;
	}

	private function get_entry_start_timestamp( $entry ) { $value = $this->value( $entry, array( 'date', 'start_date', 'start', 'datetime' ) ); return $value ? strtotime( $value ) : false; }
	private function get_entry_end_timestamp( $entry ) { $value = $this->value( $entry, array( 'date_end', 'end_date', 'end' ) ); return $value ? strtotime( $value ) : false; }
	private function date_time( $entry, $date_key, $time_key, $fallback_keys ) { $date = $this->value( $entry, array( $date_key ) ); $time = $this->value( $entry, array( $time_key ) ); return $date ? trim( $date . ( $time ? ' ' . $time : '' ) ) : $this->value( $entry, $fallback_keys ); }
	private function first_image( $entry ) { $image = isset( $entry['image'] ) ? $entry['image'] : ''; if ( is_array( $image ) ) $image = reset( $image ); return is_scalar( $image ) ? $this->normalise_url( $image ) : ''; }
	private function normalise_url( $url ) { $url = trim( (string) $url ); if ( $url && ! preg_match( '#^https?://#i', $url ) ) $url = 'https://' . $url; return $url && wp_http_validate_url( $url ) ? $url : ''; }
	private function value( $entry, $keys, $default = '' ) { foreach ( $keys as $key ) if ( isset( $entry[ $key ] ) && is_scalar( $entry[ $key ] ) && '' !== (string) $entry[ $key ] ) return (string) $entry[ $key ]; return $default; }
	private function format_date_only( $date ) { $timestamp = strtotime( $date ); return $timestamp ? wp_date( get_option( 'date_format' ), $timestamp ) : $date; }
	private function format_date( $date ) { $timestamp = strtotime( $date ); return $timestamp ? wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), $timestamp ) : $date; }
}

new JSON_Calendar_WP();
