<?php
/**
 * Plugin Name: JSON Calendar
 * Description: Fetches calendar entries from a JSON endpoint and displays them with the [json_calendar] shortcode.
 * Version: 1.3.0
 * Author: x39akkdjf1
 * License: GPL-2.0-or-later
 * Requires at least: 5.8
 * Requires PHP: 7.4
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class JSON_Calendar_WP {
	const OPTION_ENDPOINT = 'json_calendar_wp_endpoint';
	const SHORTCODE = 'json_calendar';

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_settings_page' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
		add_shortcode( self::SHORTCODE, array( $this, 'render_shortcode' ) );
	}

	public function add_settings_page() {
		add_options_page( __( 'JSON Calendar', 'json-calendar-wp' ), __( 'JSON Calendar', 'json-calendar-wp' ), 'manage_options', 'json-calendar-wp', array( $this, 'render_settings_page' ) );
	}

	public function register_settings() {
		register_setting( 'json_calendar_wp_settings', self::OPTION_ENDPOINT, array( 'type' => 'string', 'sanitize_callback' => 'esc_url_raw', 'default' => '' ) );
	}

	public function render_settings_page() {
		?>
		<div class="wrap">
			<h1><?php echo esc_html__( 'JSON Calendar', 'json-calendar-wp' ); ?></h1>
			<p><?php echo esc_html__( 'Set the URL of the JSON generated by json_calendar_generator, then add [json_calendar] to any page or post.', 'json-calendar-wp' ); ?></p>
			<form method="post" action="options.php">
				<?php settings_fields( 'json_calendar_wp_settings' ); ?>
				<table class="form-table" role="presentation">
					<tr>
						<th scope="row"><label for="json_calendar_wp_endpoint"><?php echo esc_html__( 'JSON endpoint URL', 'json-calendar-wp' ); ?></label></th>
						<td><input type="url" class="regular-text" id="json_calendar_wp_endpoint" name="<?php echo esc_attr( self::OPTION_ENDPOINT ); ?>" value="<?php echo esc_attr( get_option( self::OPTION_ENDPOINT, '' ) ); ?>" placeholder="https://example.com/kalender/199.json" required /></td>
					</tr>
				</table>
				<?php submit_button(); ?>
			</form>
		</div>
		<?php
	}

	public function render_shortcode( $atts ) {
		$atts = shortcode_atts( array( 'url' => get_option( self::OPTION_ENDPOINT, '' ), 'limit' => 0 ), $atts, self::SHORTCODE );
		$url = esc_url_raw( $atts['url'] );
		if ( empty( $url ) || ! wp_http_validate_url( $url ) ) {
			return current_user_can( 'manage_options' ) ? '<p class="json-calendar-error">' . esc_html__( 'Configure a JSON endpoint under Settings → JSON Calendar.', 'json-calendar-wp' ) . '</p>' : '';
		}

		$cache_key = 'json_calendar_' . md5( $url );
		$data = get_transient( $cache_key );
		if ( false === $data ) {
			$response = wp_safe_remote_get( $url, array( 'timeout' => 10, 'headers' => array( 'Accept' => 'application/json' ), 'user-agent' => 'JSON Calendar WordPress Plugin/1.3.0' ) );
			if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
				return '<p class="json-calendar-error">' . esc_html__( 'Calendar entries are temporarily unavailable.', 'json-calendar-wp' ) . '</p>';
			}
			$data = json_decode( wp_remote_retrieve_body( $response ), true );
			if ( JSON_ERROR_NONE !== json_last_error() ) {
				return '<p class="json-calendar-error">' . esc_html__( 'The calendar endpoint returned invalid JSON.', 'json-calendar-wp' ) . '</p>';
			}
			set_transient( $cache_key, $data, 15 * MINUTE_IN_SECONDS );
		}

		$entries = $this->get_entries( $data );
		$entries = $this->filter_future_entries( $entries );
		if ( empty( $entries ) ) {
			return '<p class="json-calendar-empty">' . esc_html__( 'No upcoming calendar entries found.', 'json-calendar-wp' ) . '</p>';
		}
		$limit = absint( $atts['limit'] );
		if ( $limit > 0 ) {
			$entries = array_slice( $entries, 0, $limit, true );
		}

		$output = '<style>.json-calendar-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:1rem;list-style:none;margin:0;padding:0}.json-calendar-entry{position:relative;overflow:hidden;min-height:180px;background:#f5f5f5}.json-calendar-image{display:block;width:100%;height:100%;min-height:180px;object-fit:cover}.json-calendar-entry:not(:has(.json-calendar-image)){padding:1rem}.json-calendar-details{position:absolute;inset:auto 0 0;padding:1rem;color:#fff;background:rgba(0,0,0,.82);transform:translateY(100%);transition:transform .2s ease}.json-calendar-entry:hover .json-calendar-details,.json-calendar-entry:focus-within .json-calendar-details{transform:translateY(0)}.json-calendar-title{margin:0 0 .4rem;font-size:1.1rem}.json-calendar-date,.json-calendar-description{display:block;margin:.3rem 0}.json-calendar-link{color:#fff}</style><div class="json-calendar"><ul class="json-calendar-list">';
		foreach ( $entries as $entry ) {
			if ( ! is_array( $entry ) ) {
				continue;
			}
			$title = $this->value( $entry, array( 'title', 'name', 'summary' ), __( 'Untitled event', 'json-calendar-wp' ) );
			$date = $this->value( $entry, array( 'date', 'start_date' ) );
			$date_end = $this->value( $entry, array( 'date_end', 'end_date' ) );
			$time_start = $this->value( $entry, array( 'time_start' ) );
			$time_end = $this->value( $entry, array( 'time_end' ) );
			$description = $this->value( $entry, array( 'description', 'details', 'content' ) );
			$link = $this->normalise_url( $this->value( $entry, array( 'url', 'link', 'permalink' ) ) );
			$image = $this->first_image( $entry );
			$start_fallback = $this->date_time( $entry, 'date', 'time_start', array( 'start', 'datetime' ) );
			$end_fallback = $this->date_time( $entry, 'date_end', 'time_end', array( 'end' ) );

			$output .= '<li class="json-calendar-entry" tabindex="0">';
			if ( $image ) {
				$output .= '<img class="json-calendar-image" src="' . esc_url( $image ) . '" alt="' . esc_attr( $title ) . '" loading="lazy" />';
			}
			$output .= '<div class="json-calendar-details"><h3 class="json-calendar-title">' . esc_html( $title ) . '</h3>';
			if ( $date || $date_end || $start_fallback ) {
				$output .= '<div class="json-calendar-date">';
				if ( $date ) {
					$output .= esc_html( $this->format_date_only( $date ) );
					if ( $date_end && $date_end !== $date ) {
						$output .= ' – ' . esc_html( $this->format_date_only( $date_end ) );
					}
				} else {
					$output .= esc_html( $this->format_date( $start_fallback ) );
				}
				$output .= '</div>';
			}
			if ( $time_start || $time_end ) {
				$output .= '<div class="json-calendar-time">' . esc_html( $time_start );
				if ( $time_end ) {
					$output .= ' – ' . esc_html( $time_end );
				}
				$output .= '</div>';
			} elseif ( $end_fallback && ! $date_end ) {
				$output .= '<div class="json-calendar-time">' . esc_html( $this->format_date( $end_fallback ) ) . '</div>';
			}
			if ( $description ) {
				$output .= '<div class="json-calendar-description">' . wp_kses_post( $description ) . '</div>';
			}
			if ( $link ) {
				$output .= '<a class="json-calendar-link" href="' . esc_url( $link ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'More information', 'json-calendar-wp' ) . '</a>';
			}
			$output .= '</div></li>';
		}
		$output .= '</ul></div>';
		return $output;
	}

	private function get_entries( $data ) {
		if ( ! is_array( $data ) ) {
			return array();
		}
		if ( isset( $data['entries'] ) && is_array( $data['entries'] ) ) {
			return $data['entries'];
		}
		if ( isset( $data['events'] ) && is_array( $data['events'] ) ) {
			return $data['events'];
		}
		$keys = array_keys( $data );
		$is_list = empty( $keys ) || $keys === range( 0, count( $keys ) - 1 );
		if ( $is_list ) {
			return $data;
		}
		$entries = array();
		foreach ( $data as $reference => $entry ) {
			if ( is_array( $entry ) ) {
				if ( empty( $entry['reference'] ) ) {
					$entry['reference'] = (string) $reference;
				}
				$entries[] = $entry;
			}
		}
		return $entries;
	}

	private function filter_future_entries( $entries ) {
		$today = strtotime( 'today' );
		$filtered = array();
		foreach ( $entries as $entry ) {
			if ( ! is_array( $entry ) ) {
				continue;
			}
			$start = $this->get_entry_start_timestamp( $entry );
			$end = $this->get_entry_end_timestamp( $entry );
			if ( false === $start && false === $end ) {
				continue;
			}
			if ( ( false !== $start && $start >= $today ) || ( false !== $end && $end >= $today ) ) {
				$filtered[] = $entry;
			}
		}
		usort(
			$filtered,
			function( $a, $b ) {
				$left = $this->get_entry_start_timestamp( $a );
				$right = $this->get_entry_start_timestamp( $b );
				if ( false === $left ) {
					$left = $this->get_entry_end_timestamp( $a );
				}
				if ( false === $right ) {
					$right = $this->get_entry_end_timestamp( $b );
				}
				if ( false === $left || false === $right ) {
					return 0;
				}
				return $left <=> $right;
			}
		);
		return $filtered;
	}

	private function get_entry_start_timestamp( $entry ) {
		$date = $this->value( $entry, array( 'date', 'start_date', 'start', 'datetime' ) );
		if ( '' === $date ) {
			return false;
		}
		$timestamp = strtotime( $date );
		return false === $timestamp ? false : $timestamp;
	}

	private function get_entry_end_timestamp( $entry ) {
		$date = $this->value( $entry, array( 'date_end', 'end_date', 'end' ) );
		if ( '' === $date ) {
			return false;
		}
		$timestamp = strtotime( $date );
		return false === $timestamp ? false : $timestamp;
	}

	private function date_time( $entry, $date_key, $time_key, $fallback_keys ) {
		$date = $this->value( $entry, array( $date_key ) );
		$time = $this->value( $entry, array( $time_key ) );
		return $date ? trim( $date . ( $time ? ' ' . $time : '' ) ) : $this->value( $entry, $fallback_keys );
	}

	private function first_image( $entry ) {
		$image = isset( $entry['image'] ) ? $entry['image'] : '';
		if ( is_array( $image ) ) {
			$image = reset( $image );
		}
		return is_scalar( $image ) ? $this->normalise_url( (string) $image ) : '';
	}

	private function normalise_url( $url ) {
		$url = trim( (string) $url );
		if ( $url && ! preg_match( '#^https?://#i', $url ) ) {
			$url = 'https://' . $url;
		}
		return $url && wp_http_validate_url( $url ) ? $url : '';
	}

	private function value( $entry, $keys, $default = '' ) {
		foreach ( $keys as $key ) {
			if ( isset( $entry[ $key ] ) && is_scalar( $entry[ $key ] ) && '' !== (string) $entry[ $key ] ) {
				return (string) $entry[ $key ];
			}
		}
		return $default;
	}

	private function format_date_only( $date ) {
		$timestamp = strtotime( $date );
		return $timestamp ? wp_date( get_option( 'date_format' ), $timestamp ) : $date;
	}

	private function format_date( $date ) {
		$timestamp = strtotime( $date );
		return $timestamp ? wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), $timestamp ) : $date;
	}
}

new JSON_Calendar_WP();
